### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by noalexan** [Nimpoo/rainfall#1]
I noticied that some sentences in README.md and probably some others files contains
translation errors. I would be nice to correct them, am i wrong?

Have a good day!

**Comment by Nimpoo** [comment]
Hi !

Yes, you're not wrong, my capacities to speak english is not perfect. I can read all my `walkthrough` and the `README.md` to correct them, you would be really nice if you help me to find all errors ! I accept that 👍🏽 ! You're really nice if you do that !

Have a good day too !
